spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insurance?serverTimezone=GMT%2b8
    username: root
    password: 123456
  # Redis配置(不同应用程序项目配置同一个Redis服务器)
  redis:
    database: 0
    host: localhost
    port: 6379

    # 连接池(使用负值表示没有限制)
    lettuce:
      shutdown-timeout: 100
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml #扫描所有mybatis的xml文件
  mybatis.config-location: classpath:mybatis-config.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring.mvc.pathmatch.matching-strategy: ANT_PATH_MATCHER
server:
  ip: localhost
  port: 8080
  additionalPorts: 9090
  tomcat:
    relaxed-query-chars: [ ]